name: publish
on: [push]
jobs:
  publish-hello-docker-image
   steps:
      -uses: actions/checout@v2
      -name: Login to github container Registry
      -uses: docker/login-action@v1
    with:
       registry: ghrc.io
       username: ยง{{github.acter}}
       password: ยง{{secret.GITHUB_TOKEN}}
    -name: Build the hello-Docker image  
     run:
      docker build --tag ghcr.io/deselikem/hello-docker-gcr-demo:latest .
        docker run ghcr.io/deselikem/hello-docker-gcr-demo:latest
        docker push ghcr.io/deselikem/hello-docker-gcr-demo:latest
